costmap:
  # Parâmetros comuns a global_costmap e local_costmap
  robot_base_frame: base_link
  transform_tolerance: 0.5
  update_frequency: 5.0
  publish_frequency: 2.0

  footprint: [[-0.3, -0.3], [-0.3, 0.3], [0.3, 0.3], [0.3, -0.3]]
  inflation_radius: 0.5
  obstacle_range: 2.5
  raytrace_range: 3.0

  observation_sources: laser_scan_sensor
  laser_scan_sensor:
    sensor_frame: sick_laser_link
    data_type: LaserScan
    topic: /scan
    marking: true
    clearing: true
