global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  transform_tolerance: 0.5
  static_map: true
  rolling_window: false
  width: 20.0
  height: 20.0
  resolution: 0.5

  plugins:
    - name: static_layer
      type: "costmap_2d::StaticLayer"
    - name: obstacle_layer
      type: "costmap_2d::ObstacleLayer"
    - name: inflation_layer
      type: "costmap_2d::InflationLayer"

  obstacle_range: 2.5
  raytrace_range: 3.0
  inflation_radius: 0.5
  footprint: [[-0.3, -0.3], [-0.3, 0.3], [0.3, 0.3], [0.3, -0.3]]

  observation_sources: laser_scan_sensor
  laser_scan_sensor:
    sensor_frame: sick_laser_link
    data_type: LaserScan
    topic: /scan
    marking: true
    clearing: true
