base_global_planner: "navfn/NavfnROS"
base_local_planner: "dwa_local_planner/DWAPlannerROS"

controller_frequency: 10.0
planner_frequency: 5.0

# Parâmetros do planner local
DWAPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.1
  max_vel_theta: 1.0
  min_in_place_vel_theta: 0.4
  acc_lim_theta: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 0.0
  yaw_goal_tolerance: 0.2
  xy_goal_tolerance: 0.2
  latch_xy_goal_tolerance: true
  sim_time: 1.5
  sim_granularity: 0.025
  vx_samples: 20
  vtheta_samples: 40
  path_distance_bias: 32.0
  goal_distance_bias: 20.0
  occdist_scale: 0.02
